---
services:
    mariadb:
        build: docker/mariadb
        working_dir: /data
        container_name: ratel_mariadb
        volumes:
            - ./db:/var/lib/mysql
            - ./docker/mariadb/config/rocksdb.cnf:/etc/mysql/mariadb.conf.d/rocksdb.cnf:ro
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ratel
            MYSQL_USER: ratel
            MYSQL_PASSWORD: ratel
        restart: always
        healthcheck:
            test: mariadb-admin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
            start_period: 5s
            interval: 10s
            timeout: 5s
            retries: 10

    web:
        image: nginx:1.27
        working_dir: /data
        container_name: ratel_nginx
        volumes:
            - ./web:/data
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./docker/nginx/install:/data/install:rw
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 8080:80
        environment:
            DB_HOST: mariadb
        depends_on:
            mariadb:
                condition: service_healthy
            php-fpm:
                condition: service_started
        restart: always

    php-fpm:
        build: docker/php-fpm
        working_dir: /data
        container_name: ratel_php-fpm
        volumes:
            - ./web:/data
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini:ro
            - ./docker/php-fpm/www.conf:/etc/php/8.3/fpm/pool.d/www.conf:ro
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        restart: always

    #OPTIONAL
    memcached:
        image: memcached
        container_name: ratel_memcached
        command:
          - --conn-limit=1024
          - --memory-limit=64
          - --threads=4
        restart: always
